name: terraform lint

on:
  # pull_request:
  workflow_dispatch:

env:
  terraform_version: 1.7.4
  terragrunt_version: 0.54.16

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.terraform_version }}
      - name: Check Terraform format
        run: terraform fmt -check -diff -recursive modules

  hclfmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check terragrunt HCL format
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ env.terraform_version }}
          tg_version: ${{ env.terragrunt_version }}
          tg_dir: ./
          tg_command: hclfmt --terragrunt-check --terragrunt-diff

  tflint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: modules
    env:
      TFLINT_CONFIG_FILE: ${{ github.workspace }}/modules/.tflint.hcl
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest
      - name: Cache plugin dir
        uses: actions/cache@v4
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('modules/.tflint.hcl') }}
      - name: Init TFLint
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Run TFLint
        run: tflint --recursive

  tfsec:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
        with:
          working_directory: modules
          tfsec_version: latest
          tfsec_formats: default
          soft_fail_commenter: true
          github_token: ${{ github.token }}
